name: angel_common
version: 1.0.0-alpha
description: Master package to install the current Angel Framework.
homepage: https://github.com/angel-dart/common
author: Tobe O <thosakwe@gmail.com>
environment:
    sdk: ">=1.19.0"
dependencies:
    angel_auth: "^1.0.0-dev"
    angel_client: "^1.0.0-dev"
    angel_compress: "^1.0.0"
    angel_configuration: "^1.0.0-dev"
    angel_cors: "^1.0.0-dev"
    angel_diagnostics: "^1.0.0-dev"
    angel_errors: "^1.0.0-dev"
    angel_framework: "^1.0.0-dev"
    angel_mongo: "^1.0.0-dev"
    angel_mustache: "^1.0.0-dev"
    angel_proxy: "^1.0.0-dev"
    angel_static: "^1.1.0-dev"
    angel_test: "^1.0.0-dev"